version: '2.4'
services:
  front:
    build: front
    restart: on-failure
    command: nodemon server.js
    volumes:
      - ./front:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5001:80"
      - "5525:5525"
    networks:
      - front-tier
      - back-tier
    links:
      - listener
  listener:
    build: listener
    restart: on-failure
    command: nodemon server.js
    volumes:
      - ./listener:/app
    networks:
      - back-tier
  github:
    build: github
    restart: on-failure
    command: nodemon server.js
    volumes:
      - ./github:/app
    networks:
      - back-tier
  logparser:
    build: logparser
    restart: on-failure
    command: nodemon server.js
    volumes:
      - ./logparser:/app
    networks:
      - back-tier
  buildsaver:
    build: plugins/buildsaver
    restart: on-failure
    command: nodemon server.js
    volumes:
      - ./plugins/buildsaver:/app
    networks:
      - back-tier
    links:
      - mongo
      - listener
  restartedbuilds:
    build: plugins/restartedbuilds
    command: nodemon server.js
    restart: on-failure
    volumes:
      - ./plugins/restartedbuilds:/app
    networks:
      - back-tier
    links:
      - mongo
    cpu_count: 2
  mongo:
    image: mongo:latest
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - back-tier
    healthcheck:
      test:
      - CMD
      - mongo
      - --eval
      - "db.adminCommand('ping')"
      interval: 10s
      timeout: 10s
      retries: 5
    cpu_count: 5
    mem_limit: 25g
volumes:
  db-data:

networks:
  front-tier:
  back-tier:
